// Writes one script per language from js/i18n.js, so a visitor downloads only
// their language's text:
//
//   js/i18n.js          the source: every text as  key: [English, Español, Português]
//                       (edited by hand; Node and the unit tests load it as is)
//   js/i18n/en.js       generated: the same window.I18n, with English text only
//   js/i18n/es.js       ... Spanish only
//   js/i18n/pt.js       ... Portuguese only
//
// The pages load js/i18n/<lang>.js (pages/layout.html), one third the size of
// the source. Each generated file offers what the pages use of window.I18n:
// t(key, vars) (an unknown key throws, like the source), lang(), locale(),
// name(), LANGS, LOCALES, NAMES and STRINGS (key: text, this language only).
// There is no setLang(): only the page's language is on board.
//
// Run by scripts/build-pages.mjs (npm run pages writes the files; npm run
// check:pages fails when one is out of date), and on its own:
//   node scripts/build-i18n.mjs           rebuild
//   node scripts/build-i18n.mjs --check   exit 1 if a file is stale

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";
import * as prettier from "prettier";

const root = fileURLToPath(new URL("..", import.meta.url));
const require = createRequire(import.meta.url);

export const I18N_DIR = "js/i18n/";

// The runtime each generated file carries, around that language's strings.
function script(lang, strings, I18n) {
  return `// GENERATED by scripts/build-i18n.mjs from js/i18n.js: do not edit, edit
// js/i18n.js and run \`npm run pages\`. The site's JavaScript text in one
// language (${I18n.NAMES[lang]}), so a page downloads only the language it shows.
// See js/i18n.js for what each key is and the full window.I18n.

(function (/** @type {any} */ root, factory) {
  "use strict";
  var api = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = api;
  } else {
    root.I18n = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  var LANG = ${JSON.stringify(lang)};
  var LANGS = ${JSON.stringify(I18n.LANGS)};
  var LOCALES = ${JSON.stringify(I18n.LOCALES)};
  var NAMES = ${JSON.stringify(I18n.NAMES)};

  var S = ${JSON.stringify(strings)};

  // t("key", { name: value }) — the text, with {name} placeholders filled in.
  function t(key, vars) {
    var text = S[key];
    if (text === undefined) throw new Error("I18n: unknown key " + key);
    if (vars) {
      text = text.replace(/\\{(\\w+)\\}/g, function (m, name) {
        return Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : m;
      });
    }
    return text;
  }

  return {
    LANGS: LANGS,
    LOCALES: LOCALES,
    NAMES: NAMES,
    STRINGS: S,
    t: t,
    lang: function () {
      return LANG;
    },
    locale: function (lang) {
      return LOCALES[lang || LANG] || LOCALES.en;
    },
    name: function (lang) {
      return NAMES[lang || LANG];
    },
  };
});
`;
}

// Every generated file: Map of path (from the repo root) to its text.
export async function buildI18n() {
  // A fresh read of the source each time (the page build may run after an edit).
  const path = require.resolve("../js/i18n.js");
  delete require.cache[path];
  const I18n = require(path);
  const out = new Map();
  for (const lang of I18n.LANGS) {
    const i = I18n.LANGS.indexOf(lang);
    const strings = {};
    for (const [key, entry] of Object.entries(I18n.STRINGS)) {
      const text = entry[i];
      strings[key] = typeof text === "string" && text ? text : entry[0];
    }
    const pretty = await prettier.format(script(lang, strings, I18n), { parser: "babel", printWidth: 120 });
    out.set(I18N_DIR + lang + ".js", pretty);
  }
  return out;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [file, text] of await buildI18n()) {
    const full = join(root, file);
    let current = "";
    try {
      current = await readFile(full, "utf8");
    } catch {
      current = "";
    }
    if (current === text) continue;
    if (check) {
      console.error(`${file} is out of date: run npm run pages`);
      stale++;
    } else {
      await mkdir(dirname(full), { recursive: true });
      await writeFile(full, text);
      console.log(`wrote ${file}`);
    }
  }
  if (stale) process.exit(1);
  if (check) console.log("Every js/i18n/<lang>.js matches js/i18n.js.");
}
